version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - aws s3 rm s3://single-spa-root-config/ --recursive
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist
